[package]
name = "pseudo-id"
version = "0.1.0"
authors = ["shumy <micaelpedrosa@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = "^1"
rand_os = "^0.1"
rand = "^0.6"
sha2 = "^0.8"
clap = "^2.33"
rayon = "^1.1"
#base64 = "^0.10"
